

[tasks.format]
description = "Format/Lint (auto-fix) Python & shell"
run = [
  ".venv/bin/ruff check src --fix",
  ".venv/bin/ruff check test --fix || true",
  "command -v shfmt >/dev/null 2>&1 && shfmt -w install.sh || echo 'shfmt not installed'"
]

[tasks.lint]
description = "Strict lint (no fixes)"
run = [
  ".venv/bin/ruff check src",
  ".venv/bin/ruff check test || true"
]

[tasks.test]
description = "Run pytest suite"
run = [
  ".venv/bin/python -m pytest -q"
]

[tasks.bump-release]
description = "Bump patch version & tag if tests pass"
run = [
  "set -e",
  "CURR=$(git describe --tags --abbrev=0 2>/dev/null | sed 's/^v//')",
  "if [[ $CURR =~ ^([0-9]+)\\.([0-9]+)\\.([0-9]+)$ ]]; then MAJOR=${BASH_REMATCH[1]}; MINOR=${BASH_REMATCH[2]}; PATCH=${BASH_REMATCH[3]}; NEW_PATCH=$((PATCH+1)); NEW_VER=\"v${MAJOR}.${MINOR}.${NEW_PATCH}\"; echo [mise] New version: $NEW_VER; git add .; git commit -m \"chore: format, lint, test, release $NEW_VER\" || echo '[mise] Nothing to commit'; git tag $NEW_VER; git push --follow-tags; else echo '[mise] Could not determine current version'; exit 1; fi"
]

[tasks.ci]
description = "Run full CI chain"
depends = ["format", "lint", "test"]
run = [
  "echo '[mise] CI tasks completed'"
]
